[package]
name = "sgp-v4"
version = "1.0.0"
description = "Sistema de Gerenciamento de Pedidos"
authors = ["SGP Team"]
license = ""
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
tauri = { version = "1.5.4", features = [ "http-request", "fs-remove-file", "fs-create-dir", "fs-write-file", "fs-read-file", "fs-exists", "path-all", "updater", "dialog-all", "shell-open", "devtools"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
